name: DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # This is the SHA for actions/checkout@v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        # This is the SHA for actions/setup-java@v4.5.0
        uses: actions/setup-java@8df1039502a1497274092b3bc1d8c1c5188f6a96
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        # This is the SHA for actions/cache@v4.2.0
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and Analyze (SAST)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify org.jacoco:jacoco-maven-plugin:prepare-agent org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=JasserGR_devops-env-monitor -Dsonar.organization=jassergr

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        # This is the SHA for docker/login-action@v3.3.0
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        # This is the SHA for docker/build-push-action@v6.13.0
        uses: docker/build-push-action@48aba373842fe3053c6a0c74af0265ad73c11e73
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/env-monitor:latest
