name: DevOps Final CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    name: Build, SAST & Docker Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Analyze (SAST)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify \
          org.jacoco:jacoco-maven-plugin:prepare-agent \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=JasserGR_devops-env-monitor \
          -Dsonar.organization=jassergr

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/env-monitor:latest

  container-security:
    name: Container Vulnerability Scan (Trivy)
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/env-monitor:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

  dast-scan:
    name: Dynamic Security Scan (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: [build-and-scan, container-security ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull and Run Docker Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/env-monitor:latest
          docker run -d -p 8086:8086 --name my-app ${{ secrets.DOCKERHUB_USERNAME }}/env-monitor:latest
          
          echo "Waiting for app to start..."
          timeout 60s bash -c 'until curl -s http://localhost:8086/actuator/health; do sleep 5; done'
          echo "App is UP!"

      - name: Fix Permissions for ZAP
        run: |
          mkdir -p .zap
          touch .zap/rules.tsv
          chmod -R 777 .

      - name: Run ZAP Baseline Scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          docker run -v ${{ github.workspace }}:/zap/wrk/:rw \
            --network=host \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8086/api/v1/environment/readings \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html \
            || true

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_json.json
            report_md.md
            report_html.html

  kubernetes-test:
    name: Kubernetes Deployment Test (KinD)
    runs-on: ubuntu-latest
    needs: [container-security, dast-scan, container-security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create KinD Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: devops-cluster

      - name: Deploy Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          echo "Waiting for Rollout..."
          kubectl wait --for=condition=ready pod -l app=env-monitor --timeout=120s
          kubectl get pods
          kubectl get svc
