steps:
  - name: Checkout Code
    # actions/checkout@v4.2.2
    uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    with:
      fetch-depth: 0

  - name: Set up JDK 17
    # actions/setup-java@v4.7.0
    uses: actions/setup-java@3a4ad324515b47c6fa0bb947d69d80b7d529ca0c
    with:
      java-version: '17'
      distribution: 'temurin'
      cache: maven

  - name: Cache SonarCloud packages
    # actions/cache@v4.2.0
    uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
    with:
      path: ~/.sonar/cache
      key: ${{ runner.os }}-sonar
      restore-keys: ${{ runner.os }}-sonar

  - name: Build and Analyze (SAST)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    run: mvn -B clean verify org.jacoco:jacoco-maven-plugin:prepare-agent org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=JasserGR_devops-env-monitor -Dsonar.organization=jassergr

  - name: Log in to Docker Hub
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    # docker/login-action@v3.3.0
    uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Build and push Docker image
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    # docker/build-push-action@v6.13.0
    uses: docker/build-push-action@48aba373842fe3053c6a0c74af0265ad73c11e73
    with:
      context: .
      push: true
      tags: ${{ secrets.DOCKERHUB_USERNAME }}/env-monitor:latest